### ISSUE TITLE
Dynamic allocation of Protocol/IP type

### ISSUE THREAD

**Issue by Bynun** [Ybalrid/kissnet#11] opened 2020-02-21 20:16 UTC
I have an issue implementing the socket class from within a wrapper class due to the class template requirement.
The idea is the wrapper class gets created, a method is called with the connection info (ip/domain name, port, tcp/udp, ssl, server/client, etc...) and the method than creates a non-blocking socket object based on those paramiters and the ip type supplied by getaddrinfo().
The best method i can think of is to have pre-defined pointers of each type and keep track of which one i'm using which can get messy when idealy i'd like to have just one pointer/object and call an init() function supplying the sock_proto and ipver that does the same as the constructors.

Would a non-templated version be possible without me having to write it myself each time a new version came out, or can you think of another way to do what i need as my C++17 knowledge is lacking (i gave up learning the new stuff back in the 90s)

p.s. Stumbled onto kissnet from the article you wrote after my own hair pulling with ASIO, loving it so far :)

**Comment by Ybalrid** [comment] 2020-02-22 01:45
I like things being static...

I'll think about your issue :)

**Comment by Bynun** [comment] 2020-02-27 13:23
While waiting i ended up re-writing the socket class to fit my needs which also resulted in rewriting other bits and moving parts to fit my style and fix errors while adding additional sanity checks within methods. Now you need to call a Create() function instead of relying on the constructor but it allows the class to be fully dynamic.
I've included a copy (it didn't allow .hpp) so you can and shake your head at the mess i've made :)
All thats left is SLL server i guess?
[kissnet.txt](https://github.com/Ybalrid/kissnet/files/4261781/kissnet.txt)

**Comment by Ybalrid** [comment] 2020-05-27 22:44
The statically initialized thing is by design. I'm closing this.

**Closed by Ybalrid** 2020-05-27 22:44 UTC
Labels: wontfix
